### ISSUE TITLE
Modify Time and Time Countdown all in one

### ISSUE THREAD

**Issue by jdteasler** [camleng/mobber#61]
_**User A**_ can be modifying the time, but doesn't reflect that a user is in the mode of changing the time. If time is started by **_User B_**, then User A can modify time while it is going down and cannot get out of it. Also, User B never knew that it was in a modified state. Maybe when one user wants to modify the time then give indication to other users in the same session that someone is modifying the time. 
![image](https://user-images.githubusercontent.com/32600621/84226501-8b352e00-aaa7-11ea-9b67-eaccaaee4e2d.png)

![image](https://user-images.githubusercontent.com/32600621/84226113-82902800-aaa6-11ea-8fe4-0dbfeef8f695.png)

**Comment by jdteasler** [comment]
Mobber session was 126058

**Comment by camleng** [comment]
Oh my gosh. When I reproduce this issue, I'm also able to reproduce that issue of it counting down by two (or there seemingly being 2 timers). Finally!
